#!/usr/bin/env bash
# This script transfers a file from our client to a server.

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    file="$1"; sip="$2"; username="$3"; key="$4"

    scp "-i" "$key" "-o" "StrictHostKeyChecking=False" "$file" "$username@$sip:~/"
fi
