#!/usr/bin/env bash
# This script install and configures a Nginx server.

apt-get update
apt-get -y install nginx

service nginx start

file="/var/www/html/index.html"
echo "Holberton School" > "$file"
