#!/usr/bin/env bash
# This script install and configures a Nginx server.

apt-get update
apt-get -y install nginx

service nginx start

file="/var/www/html/index.html"
echo "Holberton School" > "$file"

config="/etc/nginx/sites-available/default"
text="server {\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "0,/server {/s//$text/" "$config"

file2="/var/www/html/404.html"
echo "Ceci n'est pas une page" > "$file2"

text2="server {\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html\/;\n\t\tinternal;\n\t}"
sed -i "0,/server {/s//$text2/" "$config"

service nginx restart
