#!/usr/bin/env bash
# This script manages manage_my_process.

FILE="/var/run/my_process.pid"

Error (){
    echo "Usage: manage_my_process {start|stop|restart}"
    exit
}

Start() {
    ./manage_my_process & echo $$ > $FILE
}

Stop() {
    pkill -f "manage_my_process" & rm $FILE
}

Restart() {
    Stop
    Start
}

if [ $# != 1 ]; then
    Error
fi

case "$1" in
    start)
        Start & echo "manage_my_process started";;
    stop)
        Stop & echo "manage_my_process stopped";;
    restart)
        Restart & echo "manage_my_process restarted";;
    *)
        Error;;
esac
