#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays this data.

FILE="apache-access.log"
awk -F" " '{print $1" "$9}' "$FILE" | sort | uniq -c | sort -rn | sed  "s/ */    /"
