#!/usr/bin/env bash
# Displays bad luck for the 4th, good luck for the 8th loop iteration,
# else Holberton School

COUNTER=0
while [ $COUNTER -lt 10 ]; do
    if [ $COUNTER -eq 3 ]; then
        echo "bad luck"
    elif [ $COUNTER -eq 7 ]; then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((COUNTER++))
done
