#!/usr/bin/env bash
# This script configures an Ubuntu server
# Requirements:
# localhost resolves to 127.0.0.2.
# facebook.com resolves to 8.8.8.8.

FILE="/etc/hosts"
CPY="$HOME/hosts.new"

cp "$FILE" "$CPY"
sed -i "/.* localhost$/d" "$CPY"
sed -i "/.* facebook.com$/d" "$CPY"
sed -i "1 s/^/8.8.8.8 facebook.com\n/" "$CPY"
sed -i "1 s/^/127.0.0.2 localhost\n/" "$CPY"
cp -f "$CPY" "$FILE"
