#!/usr/bin/env bash
# This script configures an Ubuntu server
# Requirements:
# localhost resolves to 127.0.0.2.
# facebook.com resolves to 8.8.8.8.

FILE="/etc/hosts"
CPY="$HOME/hosts.new"

cp "$FILE" "$CPY"
sed -i "s/.*localhost$//" "$CPY"
sed -i "s/.*facebook.com$//" "$CPY"
echo "127.0.0.2 localhost" >> "$CPY"
echo "8.8.8.8 facebook.com" >> "$CPY"
cp -f "$CPY" "$FILE"
