#!/usr/bin/env bash
# This script fix that Nginx is not running as the nginx user.
pkill "apache2"
chmod 777 /etc/nginx/nginx.conf
sed -i '1 i user nginx;' /etc/nginx/nginx.conf
sed -i 's/80 default/8080 default/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
